encoding: utf-8
name: "Hürther Brücke der Kulturen"
url: "/"
giturl: "https://huerther-bruecke-der-kulturen.github.io/"
teaserstyle: "assets/stylesheets/teaser.css"
logo: "assets/images/Logo256.jpg"
tagline: "assets/images/tagline.png"
teaserjs: "assets/js/teaser.js"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "teaser"
      small-img: "assets/images/Logo256.jpg"
      teaser-bg: "assets/images/Logo256.jpg"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "two-column"
      author: "Das HBDK Team"
